### ISSUE TITLE
Unvollständig generierte Hyperlinks (Domain & E-Mail-Adresse)

### ISSUE THREAD

**Issue by PaulBeton** [grefel/createHyperlinks#3]
Hallo Gregor und **vielen Dank für deine Arbeit!**

Ich bin neu in GitHub und schreibe deutsch, weil’s einfach schneller geht ;)

Ich habe das Script in der aktuellesten Version (v2) im aktuellsten InDesign (2022/Win) genutzt und leider gleich zwei unvollständige Hyperlinks erhalten:
- Subdomains vor dem "@" bei E-Mail-Adressen werden ignoriert (bspw. "**schule.**dorf@domain.de").
- Domainteile nach Schrägstrichen leider ebenfalls (bspw. nach "facebook.com**/…**").
Geht das für einen GREP-Crack wie dich leicht zu beheben? Ich bin im Scripting leider nicht bewandert.

Ich wiederhole mich: Vielen Dank für die tolle Arbeit – natürlich nicht nur bei dem Script hier :)

Viele Grüße (in freudiger Erwartung auf eine Antwort),

Paul

PS: Parallel schreibe ich auch einen Request – dort gehört mein Wunsch nach eine PDF/UA-Anpassung wohl besser hin …?

**Comment by grefel** [comment]
Ich vermute in beiden Fällen steckt noch irgendein unerwartetes Zeichen in der URL. Ich habe gerade mit 

schule.dorf@domain.de
facebook.com/test/test 

gestestet und da klappt es gut. Kannst du die nicht funktionierenden Hyperlinks noch etwas präziser senden?

**Comment by PaulBeton** [comment]
Vielen vielen Dank für die schnellen Antworten!

Das ist die 1:1-Kopie der beiden aufeinanderfolgenden Absätze aus InDesign („envelope“ und „globe“ werden per FontAwesome zur Ligatur):
envelope 800friedersdorf.ev@gmx.de 
globe facebook.com/Dorfgemeinschaft.Friedersdorf

Hier der Screenshot dazu:
![Bsp_createHyperlinks](https://user-images.githubusercontent.com/106681222/171567671-0295d218-74f5-4069-8027-92b639149465.png)

Vielleicht sind es die Versalien und Zahlen …?

**Comment by grefel** [comment]
Sollte mit dem neuesten Commit klappen.
