### ISSUE TITLE
Möglichkeit für Alternativtext nach PDF/UA-Standard

### ISSUE THREAD

**Issue by PaulBeton** [grefel/createHyperlinks#4]
Hallo nochmal,

Ich wünsche mir eine Anpassung/Erweiterung für das Script, um die Arbeit für barrierefreie PDFs (PDF/UA) zu erleichtern. Dort wird nämlich verlangt, dass auch Hyperlinks einen Alternativtext aufweisen müssen. 
Dies für mehrere (meist: viele) Hyperlinks manuell zu bewerkstelligen, dauert jedoch eine gefühlte Ewigkeit. Und da InDesign für seine Scriptfähigkeit gelobt wird (ich leider nicht), kam mir der Gedanke, dass dies auch gleich per selbigem – dieses hier eignet sich perfekt – erledigen zu lassen. 
Im Prinzip genügt ja ein Eintrag à la "Internetseite zu …" oder "E-Mail-Adresse zu …". Und jetzt fällt mir ein, dass das schwierig wird, den Platzhalter korrekt auszufüllen – woher soll der Inhalt kommen …?
Zweite Idee dazu: Gibt es eine Möglichkeit, sich die generierten Hyperlinks per Datei oder Textmodus anzeigen zu lassen, um die geforderten Eintragungen zumindest an einer Stelle in einer Art Maske (und in einem Stück) nachzutragen?

Nochmals vielen Dank für eine Antwort,

Paul

**Comment by PaulBeton** [comment]
Entschuldigung, dass sollte ein Request werden. Das Prozedere verstehe ich hier (noch) nicht …

**Comment by grefel** [comment]
Das ist eine feine Idee. 

Die gelobte, 100% Scriptunterstüzung von InDesign hat ca. drei, vier Leerstellen. Eine davon ist der Alt-Text von Hyperlinks. Man kann ihn nicht (bzw. nur sehr, sehr aufwändig) per Script erstellen. Deswegen kann ich dieses Feature nicht implementieren. 

Du kannst aber gerne hier abstimmen, vielleicht baut Adobe es noch ein. 

https://indesign.uservoice.com/forums/601021-adobe-indesign-feature-requests/suggestions/44895820-add-alternate-text-for-hyperlinks
