### ISSUE TITLE
Colon in URLs

### ISSUE THREAD

**Issue by gregoriopellegrino** [grefel/createHyperlinks#5]
Hi,
thanks for this script. I saw that it does not correctly detect links with a colon in them, for example:

```
http://site.com/gwturl#user:45/comments
```

I have now modified the script at line 925:

```
var URLText = "(?:(?:/|/\x{E009}\n\t}?|#|:)[^\s\].,;>\"')]{2,}(?:\.[a-Z]{2,5})?"
```

I think it may be of use to others

**Comment by grefel** [comment]
Thank you for the alternative GREP expression. The case that the colon is at the end of the URL (as a punctuation mark) then leads to the punctuation mark being counted as part of the URL. Also not ideal. I'll think again about an optimized solution.
